accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"login/$", views.LoginView.as_view(), name="login"),
    url(r"logout/$", views.LogoutView.as_view(), name="logout"),
    url(r"logout/$", views.SignUpView.as_view(), name="signup"),
]

workouts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login

app_name = 'workouts'

urlpatterns = [
    
    url(r'^Home/$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)$', views.DetailView.as_view(), name='description'),
    url(r'^(?P<User_ID>[0-9]+)/user/$', views.workout_summary, name='summary'),
]

accounts/models.py
from django.db import models

# Create your models here.

workouts/models.py
from django.db import models
import os

# Create your models here.


def get_image_path(instance, filename):
    return os.path.join('photos', str(instance.id), filename)


class User(models.Model):
    UserName = models.CharField(max_length=30)
    FirstName = models.CharField(max_length=30)
    LastName = models.CharField(max_length=30)
    Position = models.CharField(max_length=10)
    email = models.EmailField(max_length=70)
    Bio_description = models.TextField()
    Profile_Pic = models.FileField()

    def __str__(self):
        return self.FirstName + ' ' + self.LastName


class Workout(models.Model):
    Workout_Name = models.CharField(max_length=100)
    Workout_Description = models.TextField()
    likes = models.IntegerField(default=0)
    Position = models.CharField(max_length=10)

    def __str__(self):
        return self.Workout_Name


class Workout_Summary(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    Workout = models.ForeignKey(Workout, on_delete=models.CASCADE)
    Date = models.DateTimeField(auto_now_add=True)
    Shots_Made = models.IntegerField()
    Shots_Attempted = models.IntegerField()

    def __str__(self):
        return "In the workout: {}, you went {}/{}".format(self.Workout, self.Shots_Made, self.Shots_Attempted)

accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import login, logout


# Create your views here.

class LoginView(generic.FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy('workouts:index')
    template_name = 'accounts/login.html'

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.request, **self.get_form_kwargs())

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)


class LogoutView(generic.RedirectView):
    url = reverse_lazy('accounts:login')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class SignUp(generic.Creatview):
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/signup.html'

workouts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Workout, User, Workout_Summary
from django.views import generic
# Create your views here.


class IndexView(generic.ListView):
    template_name = 'workouts/index.html'
    context_object_name = 'all_workouts'

    def get_queryset(self):
        return Workout.objects.all()


class DetailView(generic.DetailView):
    model = Workout
    template_name = 'workouts/Description.html'


def workout_summary(request, User_ID):
    user = get_object_or_404(User, pk=User_ID)
    summary = Workout_Summary.objects.filter(User=user)
    content = {
        'user': user,
        'summary': summary,

    }
    return render(request, 'workouts/summary.html', content)

accounts/templates/accounts/account_base.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>All About The Buckets</title>
  {% load staticfiles %}
  {% load Workouts_tags_filters %}
  <link rel="stylesheet" type="text/css" href="{% static 'workouts/CSS/styles.css' %}"/>
  <link rel="stylesheet" href="{% static 'workouts/CSS/Bootstrap/css/bootstrap.min.css' %}"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
  {% block body %}
  
  {% endblock %}
</body>

accounts/templates/accounts/login.html
{% extends 'accounts/account_base.html' %}

{% block body %}
<div class="pull-right">
  <div class="well">

    <h2 class="red-text text-center"><b>All About The Buckets</b></h2>
    <p class="re-text text-center">Login to see your workouts, communicate with
      friends, <br>and stay up to date with the</br> basketball community.</p>
    <div id="content-container" class="container p-none">
            <div class="lgn-container col-lg-8">
                <form id="login-form" method="post"
                      action="{% url 'workouts:index' %}">
                    {% csrf_token %}
                    <table class="table">
                        <tr>
                            <td><label for="id_username">Username</label></td>
                            <td><input id="id_username" name="username"
                                       type="text" class="form-control"></td>
                        </tr>
                        <tr>
                            <td><label for="id_password">Password</label></td>
                            <td><input id="id_password" name="password"
                                       type="password" class="form-control"></td>
                        </tr>
                    </table>
                    {% if form.errors %}
                        <p class=" label label-danger">
                            Your username and password didn't match.
                            Please try again.
                        </p>
                    {% endif %}

                    <input type="submit" value="Login"
                           class="btn btn-primary pull-right" />
                    <input type="hidden" name="next" value="{{ next }}" />
                </form>
            </div>
        </div>
      </div>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'accounts/account_base.html' %}

{% block body %}
<div class="pull-right">
  <div class="well">

    <h2 class="red-text text-center"><b>All About The Buckets</b></h2>
    <p class="re-text text-center">Sign up to see your workouts, communicate with
      friends, <br>and stay up to date with the</br> basketball community.</p>
    <div id="content-container" class="container p-none">
            <div class="lgn-container col-lg-8">
                <form id="login-form" method="post"
                      action="{% url 'workouts:index' %}">
                    {% csrf_token %}
                    <table class="table">
                        <tr>
                            <td><label for="id_username">Username</label></td>
                            <td><input id="id_username" name="username"
                                       type="text" class="form-control"></td>
                        </tr>
                        <tr>
                            <td><label for="id_password">Password</label></td>
                            <td><input id="id_password" name="password"
                                       type="password" class="form-control"></td>
                        </tr>
                    </table>
                    {% if form.errors %}
                        <p class=" label label-danger">
                            Your username and password didn't match.
                            Please try again.
                        </p>
                    {% endif %}

                    <input type="submit" value="Login"
                           class="btn btn-primary pull-right" />
                    <input type="hidden" name="next" value="{{ next }}" />
                </form>
            </div>
        </div>
      </div>
    </div>
{% endblock %}

workouts/templates/workouts/Base.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>All About The Buckets</title>
  {% load staticfiles %}
  {% load Workouts_tags_filters %}
  <link rel="stylesheet" type="text/css" href="{% static 'workouts/CSS/styles.css' %}"/>
  <link rel="stylesheet" href="{% static 'workouts/CSS/Bootstrap/css/bootstrap.min.css' %}"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'workouts:index' %}"><b>AATB</b></a>
      </div>
      <div class="collapse navbar-collapse" id="topNavbar">
        <ul class="nav navbar-nav">
          <li class="active">
            <a href="#">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            </a>
          </li>


        </ul>

        <form class="navbar-form navbar-left" role="search" method="get" action="#">
            <div class="form-group">
              <input type="text" class="form-control" name="query" value="">
            </div>
            <button type="submit" class="btn btn-default">
              <span class="glyphicon glyphicon-search"></span>
            </button>
        </form>

      </div>

    </div>
  </nav>

  {% block body %}
  {% endblock %}

</body>
</html>

workouts/templates/workouts/Description.html
{% extends 'workouts/Base.html' %}
{% load Workouts_tags_filters %}

{% block body %}
<a href = "{% url 'workouts:index' %}">
  <button type="button">Home page</button>
</a>
<h3>{{workout.Workout_Name}}</h3>
<p>{{workout.Workout_Description}}</p>
<p>This workout recevied {{workout.likes}} likes.</p>

{% endblock %}

workouts/templates/workouts/index.html
{% extends 'workouts/Base.html' %}
{% load Workouts_tags_filters %}


{% block body %}
  <h4> ASB X CAPMPERROL </h4>
  <h3>This is the Workouts page, let's get better!</h3>
  <ol>
      {% for workouts in all_workouts %}
      <li>
        <a href= "{% url 'workouts:description' workouts.id %}">
          <button type="button">{{workouts.Workout_Name}}</button>
        </a>
      </li>
      {% endfor %}
  </ol>
{% endblock %}

workouts/templates/workouts/summary.html
{% extends 'workouts/Base.html' %}
{% load Workouts_tags_filters %}

{% block body %}
<div class="page header"
  <h3>Workout Summary</h3>
</div>

<div class="container">

  <img src="{{user.Profile_Pic.url}}" class="ttoe">

  <h2>{{user.UserName}}</h2>
  <p class="lead"><small>{{user.Bio_description}}</small></p>

  <ul class="list-unstyled">
  {% for summaries in summary %}
  <li>
    <br>
      <h5>
        <b>Workout</b>: {{summaries.Workout.Workout_Name}}
        <br><b>Date</b>: {{summaries.Date|date:"F j, Y"}}</br>
      </h5>

        <small>
          you went {{summaries.Shots_Made}}/ {{summaries.Shots_Attempted}}.
          <b>Percentage:</b> {{summaries.Shots_Made| percentage:summaries.Shots_Attempted}}
        </small>
      </br>

  {% endfor %}
  </ul>
</div>
{% endblock %}